# coding: utf-8

"""
    billing

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class OrderInfoForListOrdersOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'buyer_customer_name': 'str',
        'buyer_id': 'int',
        'coupon_amount': 'str',
        'create_time': 'str',
        'currency_settlement': 'str',
        'discount_amount': 'str',
        'exchange_rate': 'str',
        'order_fail_refund_info': 'OrderFailRefundInfoForListOrdersOutput',
        'order_id': 'str',
        'order_type': 'str',
        'original_amount': 'str',
        'paid_amount': 'str',
        'payable_amount': 'str',
        'payer_customer_name': 'str',
        'payer_id': 'int',
        'point_deduct_amount': 'str',
        'points': 'str',
        'pre_tax_payable_amount': 'str',
        'seller_customer_name': 'str',
        'seller_id': 'int',
        'settle_payable_amount': 'str',
        'settle_tax': 'str',
        'status': 'str',
        'subject_no': 'str',
        'tax': 'str',
        'tax_rate': 'str'
    }

    attribute_map = {
        'buyer_customer_name': 'BuyerCustomerName',
        'buyer_id': 'BuyerID',
        'coupon_amount': 'CouponAmount',
        'create_time': 'CreateTime',
        'currency_settlement': 'CurrencySettlement',
        'discount_amount': 'DiscountAmount',
        'exchange_rate': 'ExchangeRate',
        'order_fail_refund_info': 'OrderFailRefundInfo',
        'order_id': 'OrderID',
        'order_type': 'OrderType',
        'original_amount': 'OriginalAmount',
        'paid_amount': 'PaidAmount',
        'payable_amount': 'PayableAmount',
        'payer_customer_name': 'PayerCustomerName',
        'payer_id': 'PayerID',
        'point_deduct_amount': 'PointDeductAmount',
        'points': 'Points',
        'pre_tax_payable_amount': 'PreTaxPayableAmount',
        'seller_customer_name': 'SellerCustomerName',
        'seller_id': 'SellerID',
        'settle_payable_amount': 'SettlePayableAmount',
        'settle_tax': 'SettleTax',
        'status': 'Status',
        'subject_no': 'SubjectNo',
        'tax': 'Tax',
        'tax_rate': 'TaxRate'
    }

    def __init__(self, buyer_customer_name=None, buyer_id=None, coupon_amount=None, create_time=None, currency_settlement=None, discount_amount=None, exchange_rate=None, order_fail_refund_info=None, order_id=None, order_type=None, original_amount=None, paid_amount=None, payable_amount=None, payer_customer_name=None, payer_id=None, point_deduct_amount=None, points=None, pre_tax_payable_amount=None, seller_customer_name=None, seller_id=None, settle_payable_amount=None, settle_tax=None, status=None, subject_no=None, tax=None, tax_rate=None, _configuration=None):  # noqa: E501
        """OrderInfoForListOrdersOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._buyer_customer_name = None
        self._buyer_id = None
        self._coupon_amount = None
        self._create_time = None
        self._currency_settlement = None
        self._discount_amount = None
        self._exchange_rate = None
        self._order_fail_refund_info = None
        self._order_id = None
        self._order_type = None
        self._original_amount = None
        self._paid_amount = None
        self._payable_amount = None
        self._payer_customer_name = None
        self._payer_id = None
        self._point_deduct_amount = None
        self._points = None
        self._pre_tax_payable_amount = None
        self._seller_customer_name = None
        self._seller_id = None
        self._settle_payable_amount = None
        self._settle_tax = None
        self._status = None
        self._subject_no = None
        self._tax = None
        self._tax_rate = None
        self.discriminator = None

        if buyer_customer_name is not None:
            self.buyer_customer_name = buyer_customer_name
        if buyer_id is not None:
            self.buyer_id = buyer_id
        if coupon_amount is not None:
            self.coupon_amount = coupon_amount
        if create_time is not None:
            self.create_time = create_time
        if currency_settlement is not None:
            self.currency_settlement = currency_settlement
        if discount_amount is not None:
            self.discount_amount = discount_amount
        if exchange_rate is not None:
            self.exchange_rate = exchange_rate
        if order_fail_refund_info is not None:
            self.order_fail_refund_info = order_fail_refund_info
        if order_id is not None:
            self.order_id = order_id
        if order_type is not None:
            self.order_type = order_type
        if original_amount is not None:
            self.original_amount = original_amount
        if paid_amount is not None:
            self.paid_amount = paid_amount
        if payable_amount is not None:
            self.payable_amount = payable_amount
        if payer_customer_name is not None:
            self.payer_customer_name = payer_customer_name
        if payer_id is not None:
            self.payer_id = payer_id
        if point_deduct_amount is not None:
            self.point_deduct_amount = point_deduct_amount
        if points is not None:
            self.points = points
        if pre_tax_payable_amount is not None:
            self.pre_tax_payable_amount = pre_tax_payable_amount
        if seller_customer_name is not None:
            self.seller_customer_name = seller_customer_name
        if seller_id is not None:
            self.seller_id = seller_id
        if settle_payable_amount is not None:
            self.settle_payable_amount = settle_payable_amount
        if settle_tax is not None:
            self.settle_tax = settle_tax
        if status is not None:
            self.status = status
        if subject_no is not None:
            self.subject_no = subject_no
        if tax is not None:
            self.tax = tax
        if tax_rate is not None:
            self.tax_rate = tax_rate

    @property
    def buyer_customer_name(self):
        """Gets the buyer_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The buyer_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._buyer_customer_name

    @buyer_customer_name.setter
    def buyer_customer_name(self, buyer_customer_name):
        """Sets the buyer_customer_name of this OrderInfoForListOrdersOutput.


        :param buyer_customer_name: The buyer_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._buyer_customer_name = buyer_customer_name

    @property
    def buyer_id(self):
        """Gets the buyer_id of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The buyer_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: int
        """
        return self._buyer_id

    @buyer_id.setter
    def buyer_id(self, buyer_id):
        """Sets the buyer_id of this OrderInfoForListOrdersOutput.


        :param buyer_id: The buyer_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: int
        """

        self._buyer_id = buyer_id

    @property
    def coupon_amount(self):
        """Gets the coupon_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The coupon_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._coupon_amount

    @coupon_amount.setter
    def coupon_amount(self, coupon_amount):
        """Sets the coupon_amount of this OrderInfoForListOrdersOutput.


        :param coupon_amount: The coupon_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._coupon_amount = coupon_amount

    @property
    def create_time(self):
        """Gets the create_time of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The create_time of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this OrderInfoForListOrdersOutput.


        :param create_time: The create_time of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def currency_settlement(self):
        """Gets the currency_settlement of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The currency_settlement of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._currency_settlement

    @currency_settlement.setter
    def currency_settlement(self, currency_settlement):
        """Sets the currency_settlement of this OrderInfoForListOrdersOutput.


        :param currency_settlement: The currency_settlement of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._currency_settlement = currency_settlement

    @property
    def discount_amount(self):
        """Gets the discount_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The discount_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._discount_amount

    @discount_amount.setter
    def discount_amount(self, discount_amount):
        """Sets the discount_amount of this OrderInfoForListOrdersOutput.


        :param discount_amount: The discount_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._discount_amount = discount_amount

    @property
    def exchange_rate(self):
        """Gets the exchange_rate of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The exchange_rate of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._exchange_rate

    @exchange_rate.setter
    def exchange_rate(self, exchange_rate):
        """Sets the exchange_rate of this OrderInfoForListOrdersOutput.


        :param exchange_rate: The exchange_rate of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._exchange_rate = exchange_rate

    @property
    def order_fail_refund_info(self):
        """Gets the order_fail_refund_info of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The order_fail_refund_info of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: OrderFailRefundInfoForListOrdersOutput
        """
        return self._order_fail_refund_info

    @order_fail_refund_info.setter
    def order_fail_refund_info(self, order_fail_refund_info):
        """Sets the order_fail_refund_info of this OrderInfoForListOrdersOutput.


        :param order_fail_refund_info: The order_fail_refund_info of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: OrderFailRefundInfoForListOrdersOutput
        """

        self._order_fail_refund_info = order_fail_refund_info

    @property
    def order_id(self):
        """Gets the order_id of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The order_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this OrderInfoForListOrdersOutput.


        :param order_id: The order_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._order_id = order_id

    @property
    def order_type(self):
        """Gets the order_type of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The order_type of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._order_type

    @order_type.setter
    def order_type(self, order_type):
        """Sets the order_type of this OrderInfoForListOrdersOutput.


        :param order_type: The order_type of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._order_type = order_type

    @property
    def original_amount(self):
        """Gets the original_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The original_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._original_amount

    @original_amount.setter
    def original_amount(self, original_amount):
        """Sets the original_amount of this OrderInfoForListOrdersOutput.


        :param original_amount: The original_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._original_amount = original_amount

    @property
    def paid_amount(self):
        """Gets the paid_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The paid_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._paid_amount

    @paid_amount.setter
    def paid_amount(self, paid_amount):
        """Sets the paid_amount of this OrderInfoForListOrdersOutput.


        :param paid_amount: The paid_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._paid_amount = paid_amount

    @property
    def payable_amount(self):
        """Gets the payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._payable_amount

    @payable_amount.setter
    def payable_amount(self, payable_amount):
        """Sets the payable_amount of this OrderInfoForListOrdersOutput.


        :param payable_amount: The payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._payable_amount = payable_amount

    @property
    def payer_customer_name(self):
        """Gets the payer_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The payer_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._payer_customer_name

    @payer_customer_name.setter
    def payer_customer_name(self, payer_customer_name):
        """Sets the payer_customer_name of this OrderInfoForListOrdersOutput.


        :param payer_customer_name: The payer_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._payer_customer_name = payer_customer_name

    @property
    def payer_id(self):
        """Gets the payer_id of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The payer_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: int
        """
        return self._payer_id

    @payer_id.setter
    def payer_id(self, payer_id):
        """Sets the payer_id of this OrderInfoForListOrdersOutput.


        :param payer_id: The payer_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: int
        """

        self._payer_id = payer_id

    @property
    def point_deduct_amount(self):
        """Gets the point_deduct_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The point_deduct_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._point_deduct_amount

    @point_deduct_amount.setter
    def point_deduct_amount(self, point_deduct_amount):
        """Sets the point_deduct_amount of this OrderInfoForListOrdersOutput.


        :param point_deduct_amount: The point_deduct_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._point_deduct_amount = point_deduct_amount

    @property
    def points(self):
        """Gets the points of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The points of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._points

    @points.setter
    def points(self, points):
        """Sets the points of this OrderInfoForListOrdersOutput.


        :param points: The points of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._points = points

    @property
    def pre_tax_payable_amount(self):
        """Gets the pre_tax_payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The pre_tax_payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._pre_tax_payable_amount

    @pre_tax_payable_amount.setter
    def pre_tax_payable_amount(self, pre_tax_payable_amount):
        """Sets the pre_tax_payable_amount of this OrderInfoForListOrdersOutput.


        :param pre_tax_payable_amount: The pre_tax_payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._pre_tax_payable_amount = pre_tax_payable_amount

    @property
    def seller_customer_name(self):
        """Gets the seller_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The seller_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._seller_customer_name

    @seller_customer_name.setter
    def seller_customer_name(self, seller_customer_name):
        """Sets the seller_customer_name of this OrderInfoForListOrdersOutput.


        :param seller_customer_name: The seller_customer_name of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._seller_customer_name = seller_customer_name

    @property
    def seller_id(self):
        """Gets the seller_id of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The seller_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: int
        """
        return self._seller_id

    @seller_id.setter
    def seller_id(self, seller_id):
        """Sets the seller_id of this OrderInfoForListOrdersOutput.


        :param seller_id: The seller_id of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: int
        """

        self._seller_id = seller_id

    @property
    def settle_payable_amount(self):
        """Gets the settle_payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The settle_payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._settle_payable_amount

    @settle_payable_amount.setter
    def settle_payable_amount(self, settle_payable_amount):
        """Sets the settle_payable_amount of this OrderInfoForListOrdersOutput.


        :param settle_payable_amount: The settle_payable_amount of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._settle_payable_amount = settle_payable_amount

    @property
    def settle_tax(self):
        """Gets the settle_tax of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The settle_tax of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._settle_tax

    @settle_tax.setter
    def settle_tax(self, settle_tax):
        """Sets the settle_tax of this OrderInfoForListOrdersOutput.


        :param settle_tax: The settle_tax of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._settle_tax = settle_tax

    @property
    def status(self):
        """Gets the status of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The status of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrderInfoForListOrdersOutput.


        :param status: The status of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def subject_no(self):
        """Gets the subject_no of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The subject_no of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._subject_no

    @subject_no.setter
    def subject_no(self, subject_no):
        """Sets the subject_no of this OrderInfoForListOrdersOutput.


        :param subject_no: The subject_no of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._subject_no = subject_no

    @property
    def tax(self):
        """Gets the tax of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The tax of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._tax

    @tax.setter
    def tax(self, tax):
        """Sets the tax of this OrderInfoForListOrdersOutput.


        :param tax: The tax of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._tax = tax

    @property
    def tax_rate(self):
        """Gets the tax_rate of this OrderInfoForListOrdersOutput.  # noqa: E501


        :return: The tax_rate of this OrderInfoForListOrdersOutput.  # noqa: E501
        :rtype: str
        """
        return self._tax_rate

    @tax_rate.setter
    def tax_rate(self, tax_rate):
        """Sets the tax_rate of this OrderInfoForListOrdersOutput.


        :param tax_rate: The tax_rate of this OrderInfoForListOrdersOutput.  # noqa: E501
        :type: str
        """

        self._tax_rate = tax_rate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderInfoForListOrdersOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderInfoForListOrdersOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderInfoForListOrdersOutput):
            return True

        return self.to_dict() != other.to_dict()
