# coding: utf-8

"""
    i18n_openapi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class DataForVideoProjectBatchReuploadForSubtasksOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resumed_subtask_ids': 'list[str]'
    }

    attribute_map = {
        'resumed_subtask_ids': 'resumedSubtaskIDs'
    }

    def __init__(self, resumed_subtask_ids=None, _configuration=None):  # noqa: E501
        """DataForVideoProjectBatchReuploadForSubtasksOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._resumed_subtask_ids = None
        self.discriminator = None

        if resumed_subtask_ids is not None:
            self.resumed_subtask_ids = resumed_subtask_ids

    @property
    def resumed_subtask_ids(self):
        """Gets the resumed_subtask_ids of this DataForVideoProjectBatchReuploadForSubtasksOutput.  # noqa: E501


        :return: The resumed_subtask_ids of this DataForVideoProjectBatchReuploadForSubtasksOutput.  # noqa: E501
        :rtype: list[str]
        """
        return self._resumed_subtask_ids

    @resumed_subtask_ids.setter
    def resumed_subtask_ids(self, resumed_subtask_ids):
        """Sets the resumed_subtask_ids of this DataForVideoProjectBatchReuploadForSubtasksOutput.


        :param resumed_subtask_ids: The resumed_subtask_ids of this DataForVideoProjectBatchReuploadForSubtasksOutput.  # noqa: E501
        :type: list[str]
        """

        self._resumed_subtask_ids = resumed_subtask_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataForVideoProjectBatchReuploadForSubtasksOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataForVideoProjectBatchReuploadForSubtasksOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataForVideoProjectBatchReuploadForSubtasksOutput):
            return True

        return self.to_dict() != other.to_dict()
