# coding: utf-8

"""
    i18n_openapi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'resource_type': 'int',
        'subtask_id': 'str',
        'subtitle_file_info': 'SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput',
        'url': 'str',
        'vid': 'str'
    }

    attribute_map = {
        'name': 'name',
        'resource_type': 'resourceType',
        'subtask_id': 'subtaskId',
        'subtitle_file_info': 'subtitleFileInfo',
        'url': 'url',
        'vid': 'vid'
    }

    def __init__(self, name=None, resource_type=None, subtask_id=None, subtitle_file_info=None, url=None, vid=None, _configuration=None):  # noqa: E501
        """ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._resource_type = None
        self._subtask_id = None
        self._subtitle_file_info = None
        self._url = None
        self._vid = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if resource_type is not None:
            self.resource_type = resource_type
        if subtask_id is not None:
            self.subtask_id = subtask_id
        if subtitle_file_info is not None:
            self.subtitle_file_info = subtitle_file_info
        if url is not None:
            self.url = url
        if vid is not None:
            self.vid = vid

    @property
    def name(self):
        """Gets the name of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The name of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param name: The name of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def resource_type(self):
        """Gets the resource_type of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The resource_type of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: int
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param resource_type: The resource_type of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: int
        """

        self._resource_type = resource_type

    @property
    def subtask_id(self):
        """Gets the subtask_id of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The subtask_id of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: str
        """
        return self._subtask_id

    @subtask_id.setter
    def subtask_id(self, subtask_id):
        """Sets the subtask_id of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param subtask_id: The subtask_id of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: str
        """

        self._subtask_id = subtask_id

    @property
    def subtitle_file_info(self):
        """Gets the subtitle_file_info of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The subtitle_file_info of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput
        """
        return self._subtitle_file_info

    @subtitle_file_info.setter
    def subtitle_file_info(self, subtitle_file_info):
        """Sets the subtitle_file_info of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param subtitle_file_info: The subtitle_file_info of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput
        """

        self._subtitle_file_info = subtitle_file_info

    @property
    def url(self):
        """Gets the url of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The url of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param url: The url of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def vid(self):
        """Gets the vid of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The vid of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: str
        """
        return self._vid

    @vid.setter
    def vid(self, vid):
        """Sets the vid of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param vid: The vid of this ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: str
        """

        self._vid = vid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ReuploadSubtaskInfoForVideoProjectBatchReuploadForSubtasksInput):
            return True

        return self.to_dict() != other.to_dict()
