# coding: utf-8

"""
    i18n_openapi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'arrangement': 'int',
        'effect_type': 'int',
        'file_name': 'str',
        'file_type': 'int',
        'file_url': 'str',
        'subtitle_id': 'str',
        'subtitle_lang': 'int'
    }

    attribute_map = {
        'arrangement': 'arrangement',
        'effect_type': 'effectType',
        'file_name': 'fileName',
        'file_type': 'fileType',
        'file_url': 'fileUrl',
        'subtitle_id': 'subtitleId',
        'subtitle_lang': 'subtitleLang'
    }

    def __init__(self, arrangement=None, effect_type=None, file_name=None, file_type=None, file_url=None, subtitle_id=None, subtitle_lang=None, _configuration=None):  # noqa: E501
        """SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._arrangement = None
        self._effect_type = None
        self._file_name = None
        self._file_type = None
        self._file_url = None
        self._subtitle_id = None
        self._subtitle_lang = None
        self.discriminator = None

        if arrangement is not None:
            self.arrangement = arrangement
        if effect_type is not None:
            self.effect_type = effect_type
        if file_name is not None:
            self.file_name = file_name
        if file_type is not None:
            self.file_type = file_type
        if file_url is not None:
            self.file_url = file_url
        if subtitle_id is not None:
            self.subtitle_id = subtitle_id
        if subtitle_lang is not None:
            self.subtitle_lang = subtitle_lang

    @property
    def arrangement(self):
        """Gets the arrangement of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The arrangement of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: int
        """
        return self._arrangement

    @arrangement.setter
    def arrangement(self, arrangement):
        """Sets the arrangement of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param arrangement: The arrangement of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: int
        """

        self._arrangement = arrangement

    @property
    def effect_type(self):
        """Gets the effect_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The effect_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: int
        """
        return self._effect_type

    @effect_type.setter
    def effect_type(self, effect_type):
        """Sets the effect_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param effect_type: The effect_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: int
        """

        self._effect_type = effect_type

    @property
    def file_name(self):
        """Gets the file_name of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The file_name of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param file_name: The file_name of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def file_type(self):
        """Gets the file_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The file_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: int
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type):
        """Sets the file_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param file_type: The file_type of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: int
        """

        self._file_type = file_type

    @property
    def file_url(self):
        """Gets the file_url of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The file_url of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: str
        """
        return self._file_url

    @file_url.setter
    def file_url(self, file_url):
        """Sets the file_url of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param file_url: The file_url of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: str
        """

        self._file_url = file_url

    @property
    def subtitle_id(self):
        """Gets the subtitle_id of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The subtitle_id of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: str
        """
        return self._subtitle_id

    @subtitle_id.setter
    def subtitle_id(self, subtitle_id):
        """Sets the subtitle_id of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param subtitle_id: The subtitle_id of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: str
        """

        self._subtitle_id = subtitle_id

    @property
    def subtitle_lang(self):
        """Gets the subtitle_lang of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501


        :return: The subtitle_lang of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :rtype: int
        """
        return self._subtitle_lang

    @subtitle_lang.setter
    def subtitle_lang(self, subtitle_lang):
        """Sets the subtitle_lang of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.


        :param subtitle_lang: The subtitle_lang of this SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput.  # noqa: E501
        :type: int
        """

        self._subtitle_lang = subtitle_lang

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SubtitleFileInfoForVideoProjectBatchReuploadForSubtasksInput):
            return True

        return self.to_dict() != other.to_dict()
