# coding: utf-8

"""
    vke

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class CreateInspectionPolicyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_token': 'str',
        'cluster_id': 'str',
        'enabled': 'bool',
        'name': 'str',
        'resource_ids': 'list[str]',
        'resource_type': 'str',
        'schedule': 'str',
        'type': 'str'
    }

    attribute_map = {
        'client_token': 'ClientToken',
        'cluster_id': 'ClusterId',
        'enabled': 'Enabled',
        'name': 'Name',
        'resource_ids': 'ResourceIds',
        'resource_type': 'ResourceType',
        'schedule': 'Schedule',
        'type': 'Type'
    }

    def __init__(self, client_token=None, cluster_id=None, enabled=None, name=None, resource_ids=None, resource_type=None, schedule=None, type=None, _configuration=None):  # noqa: E501
        """CreateInspectionPolicyRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_token = None
        self._cluster_id = None
        self._enabled = None
        self._name = None
        self._resource_ids = None
        self._resource_type = None
        self._schedule = None
        self._type = None
        self.discriminator = None

        if client_token is not None:
            self.client_token = client_token
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if enabled is not None:
            self.enabled = enabled
        if name is not None:
            self.name = name
        if resource_ids is not None:
            self.resource_ids = resource_ids
        self.resource_type = resource_type
        if schedule is not None:
            self.schedule = schedule
        self.type = type

    @property
    def client_token(self):
        """Gets the client_token of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The client_token of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_token

    @client_token.setter
    def client_token(self, client_token):
        """Sets the client_token of this CreateInspectionPolicyRequest.


        :param client_token: The client_token of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: str
        """

        self._client_token = client_token

    @property
    def cluster_id(self):
        """Gets the cluster_id of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The cluster_id of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this CreateInspectionPolicyRequest.


        :param cluster_id: The cluster_id of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: str
        """

        self._cluster_id = cluster_id

    @property
    def enabled(self):
        """Gets the enabled of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The enabled of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this CreateInspectionPolicyRequest.


        :param enabled: The enabled of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def name(self):
        """Gets the name of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The name of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateInspectionPolicyRequest.


        :param name: The name of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def resource_ids(self):
        """Gets the resource_ids of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The resource_ids of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._resource_ids

    @resource_ids.setter
    def resource_ids(self, resource_ids):
        """Sets the resource_ids of this CreateInspectionPolicyRequest.


        :param resource_ids: The resource_ids of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: list[str]
        """

        self._resource_ids = resource_ids

    @property
    def resource_type(self):
        """Gets the resource_type of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The resource_type of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this CreateInspectionPolicyRequest.


        :param resource_type: The resource_type of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and resource_type is None:
            raise ValueError("Invalid value for `resource_type`, must not be `None`")  # noqa: E501

        self._resource_type = resource_type

    @property
    def schedule(self):
        """Gets the schedule of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The schedule of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this CreateInspectionPolicyRequest.


        :param schedule: The schedule of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: str
        """

        self._schedule = schedule

    @property
    def type(self):
        """Gets the type of this CreateInspectionPolicyRequest.  # noqa: E501


        :return: The type of this CreateInspectionPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CreateInspectionPolicyRequest.


        :param type: The type of this CreateInspectionPolicyRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateInspectionPolicyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateInspectionPolicyRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateInspectionPolicyRequest):
            return True

        return self.to_dict() != other.to_dict()
