# coding: utf-8

"""
    vke

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class CreateDiagnosticTaskRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_token': 'str',
        'params': 'list[ParamForCreateDiagnosticTaskInput]',
        'target_resources': 'list[TargetResourceForCreateDiagnosticTaskInput]',
        'type': 'str'
    }

    attribute_map = {
        'client_token': 'ClientToken',
        'params': 'Params',
        'target_resources': 'TargetResources',
        'type': 'Type'
    }

    def __init__(self, client_token=None, params=None, target_resources=None, type=None, _configuration=None):  # noqa: E501
        """CreateDiagnosticTaskRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_token = None
        self._params = None
        self._target_resources = None
        self._type = None
        self.discriminator = None

        if client_token is not None:
            self.client_token = client_token
        if params is not None:
            self.params = params
        if target_resources is not None:
            self.target_resources = target_resources
        self.type = type

    @property
    def client_token(self):
        """Gets the client_token of this CreateDiagnosticTaskRequest.  # noqa: E501


        :return: The client_token of this CreateDiagnosticTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_token

    @client_token.setter
    def client_token(self, client_token):
        """Sets the client_token of this CreateDiagnosticTaskRequest.


        :param client_token: The client_token of this CreateDiagnosticTaskRequest.  # noqa: E501
        :type: str
        """

        self._client_token = client_token

    @property
    def params(self):
        """Gets the params of this CreateDiagnosticTaskRequest.  # noqa: E501


        :return: The params of this CreateDiagnosticTaskRequest.  # noqa: E501
        :rtype: list[ParamForCreateDiagnosticTaskInput]
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this CreateDiagnosticTaskRequest.


        :param params: The params of this CreateDiagnosticTaskRequest.  # noqa: E501
        :type: list[ParamForCreateDiagnosticTaskInput]
        """

        self._params = params

    @property
    def target_resources(self):
        """Gets the target_resources of this CreateDiagnosticTaskRequest.  # noqa: E501


        :return: The target_resources of this CreateDiagnosticTaskRequest.  # noqa: E501
        :rtype: list[TargetResourceForCreateDiagnosticTaskInput]
        """
        return self._target_resources

    @target_resources.setter
    def target_resources(self, target_resources):
        """Sets the target_resources of this CreateDiagnosticTaskRequest.


        :param target_resources: The target_resources of this CreateDiagnosticTaskRequest.  # noqa: E501
        :type: list[TargetResourceForCreateDiagnosticTaskInput]
        """

        self._target_resources = target_resources

    @property
    def type(self):
        """Gets the type of this CreateDiagnosticTaskRequest.  # noqa: E501


        :return: The type of this CreateDiagnosticTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CreateDiagnosticTaskRequest.


        :param type: The type of this CreateDiagnosticTaskRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateDiagnosticTaskRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateDiagnosticTaskRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateDiagnosticTaskRequest):
            return True

        return self.to_dict() != other.to_dict()
