# coding: utf-8

"""
    vke

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class FilterForListDiagnosticTaskInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_time': 'str',
        'ids': 'list[str]',
        'params': 'list[ParamForListDiagnosticTaskInput]',
        'start_time': 'str',
        'statuses': 'list[str]',
        'target_resources_resource_ids': 'list[str]',
        'target_resources_resource_types': 'list[str]',
        'types': 'list[str]'
    }

    attribute_map = {
        'end_time': 'EndTime',
        'ids': 'Ids',
        'params': 'Params',
        'start_time': 'StartTime',
        'statuses': 'Statuses',
        'target_resources_resource_ids': 'TargetResources.ResourceIds',
        'target_resources_resource_types': 'TargetResources.ResourceTypes',
        'types': 'Types'
    }

    def __init__(self, end_time=None, ids=None, params=None, start_time=None, statuses=None, target_resources_resource_ids=None, target_resources_resource_types=None, types=None, _configuration=None):  # noqa: E501
        """FilterForListDiagnosticTaskInput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._end_time = None
        self._ids = None
        self._params = None
        self._start_time = None
        self._statuses = None
        self._target_resources_resource_ids = None
        self._target_resources_resource_types = None
        self._types = None
        self.discriminator = None

        if end_time is not None:
            self.end_time = end_time
        if ids is not None:
            self.ids = ids
        if params is not None:
            self.params = params
        if start_time is not None:
            self.start_time = start_time
        if statuses is not None:
            self.statuses = statuses
        if target_resources_resource_ids is not None:
            self.target_resources_resource_ids = target_resources_resource_ids
        if target_resources_resource_types is not None:
            self.target_resources_resource_types = target_resources_resource_types
        if types is not None:
            self.types = types

    @property
    def end_time(self):
        """Gets the end_time of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The end_time of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this FilterForListDiagnosticTaskInput.


        :param end_time: The end_time of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: str
        """

        self._end_time = end_time

    @property
    def ids(self):
        """Gets the ids of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The ids of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._ids

    @ids.setter
    def ids(self, ids):
        """Sets the ids of this FilterForListDiagnosticTaskInput.


        :param ids: The ids of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: list[str]
        """

        self._ids = ids

    @property
    def params(self):
        """Gets the params of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The params of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: list[ParamForListDiagnosticTaskInput]
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this FilterForListDiagnosticTaskInput.


        :param params: The params of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: list[ParamForListDiagnosticTaskInput]
        """

        self._params = params

    @property
    def start_time(self):
        """Gets the start_time of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The start_time of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this FilterForListDiagnosticTaskInput.


        :param start_time: The start_time of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: str
        """

        self._start_time = start_time

    @property
    def statuses(self):
        """Gets the statuses of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The statuses of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._statuses

    @statuses.setter
    def statuses(self, statuses):
        """Sets the statuses of this FilterForListDiagnosticTaskInput.


        :param statuses: The statuses of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: list[str]
        """

        self._statuses = statuses

    @property
    def target_resources_resource_ids(self):
        """Gets the target_resources_resource_ids of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The target_resources_resource_ids of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._target_resources_resource_ids

    @target_resources_resource_ids.setter
    def target_resources_resource_ids(self, target_resources_resource_ids):
        """Sets the target_resources_resource_ids of this FilterForListDiagnosticTaskInput.


        :param target_resources_resource_ids: The target_resources_resource_ids of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: list[str]
        """

        self._target_resources_resource_ids = target_resources_resource_ids

    @property
    def target_resources_resource_types(self):
        """Gets the target_resources_resource_types of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The target_resources_resource_types of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._target_resources_resource_types

    @target_resources_resource_types.setter
    def target_resources_resource_types(self, target_resources_resource_types):
        """Sets the target_resources_resource_types of this FilterForListDiagnosticTaskInput.


        :param target_resources_resource_types: The target_resources_resource_types of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: list[str]
        """

        self._target_resources_resource_types = target_resources_resource_types

    @property
    def types(self):
        """Gets the types of this FilterForListDiagnosticTaskInput.  # noqa: E501


        :return: The types of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :rtype: list[str]
        """
        return self._types

    @types.setter
    def types(self, types):
        """Sets the types of this FilterForListDiagnosticTaskInput.


        :param types: The types of this FilterForListDiagnosticTaskInput.  # noqa: E501
        :type: list[str]
        """

        self._types = types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilterForListDiagnosticTaskInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilterForListDiagnosticTaskInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FilterForListDiagnosticTaskInput):
            return True

        return self.to_dict() != other.to_dict()
