# coding: utf-8

"""
    vke

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ItemForListDiagnosticTaskOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_time': 'str',
        'id': 'str',
        'params': 'list[ParamForListDiagnosticTaskOutput]',
        'reason': 'str',
        'resources_summaries': 'list[ResourcesSummaryForListDiagnosticTaskOutput]',
        'result_summaries': 'list[ResultSummaryForListDiagnosticTaskOutput]',
        'start_time': 'str',
        'status': 'int',
        'suggestion': 'str',
        'target_resources': 'list[TargetResourceForListDiagnosticTaskOutput]',
        'type': 'str'
    }

    attribute_map = {
        'end_time': 'EndTime',
        'id': 'Id',
        'params': 'Params',
        'reason': 'Reason',
        'resources_summaries': 'ResourcesSummaries',
        'result_summaries': 'ResultSummaries',
        'start_time': 'StartTime',
        'status': 'Status',
        'suggestion': 'Suggestion',
        'target_resources': 'TargetResources',
        'type': 'Type'
    }

    def __init__(self, end_time=None, id=None, params=None, reason=None, resources_summaries=None, result_summaries=None, start_time=None, status=None, suggestion=None, target_resources=None, type=None, _configuration=None):  # noqa: E501
        """ItemForListDiagnosticTaskOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._end_time = None
        self._id = None
        self._params = None
        self._reason = None
        self._resources_summaries = None
        self._result_summaries = None
        self._start_time = None
        self._status = None
        self._suggestion = None
        self._target_resources = None
        self._type = None
        self.discriminator = None

        if end_time is not None:
            self.end_time = end_time
        if id is not None:
            self.id = id
        if params is not None:
            self.params = params
        if reason is not None:
            self.reason = reason
        if resources_summaries is not None:
            self.resources_summaries = resources_summaries
        if result_summaries is not None:
            self.result_summaries = result_summaries
        if start_time is not None:
            self.start_time = start_time
        if status is not None:
            self.status = status
        if suggestion is not None:
            self.suggestion = suggestion
        if target_resources is not None:
            self.target_resources = target_resources
        if type is not None:
            self.type = type

    @property
    def end_time(self):
        """Gets the end_time of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The end_time of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this ItemForListDiagnosticTaskOutput.


        :param end_time: The end_time of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: str
        """

        self._end_time = end_time

    @property
    def id(self):
        """Gets the id of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The id of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ItemForListDiagnosticTaskOutput.


        :param id: The id of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def params(self):
        """Gets the params of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The params of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: list[ParamForListDiagnosticTaskOutput]
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this ItemForListDiagnosticTaskOutput.


        :param params: The params of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: list[ParamForListDiagnosticTaskOutput]
        """

        self._params = params

    @property
    def reason(self):
        """Gets the reason of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The reason of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ItemForListDiagnosticTaskOutput.


        :param reason: The reason of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def resources_summaries(self):
        """Gets the resources_summaries of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The resources_summaries of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: list[ResourcesSummaryForListDiagnosticTaskOutput]
        """
        return self._resources_summaries

    @resources_summaries.setter
    def resources_summaries(self, resources_summaries):
        """Sets the resources_summaries of this ItemForListDiagnosticTaskOutput.


        :param resources_summaries: The resources_summaries of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: list[ResourcesSummaryForListDiagnosticTaskOutput]
        """

        self._resources_summaries = resources_summaries

    @property
    def result_summaries(self):
        """Gets the result_summaries of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The result_summaries of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: list[ResultSummaryForListDiagnosticTaskOutput]
        """
        return self._result_summaries

    @result_summaries.setter
    def result_summaries(self, result_summaries):
        """Sets the result_summaries of this ItemForListDiagnosticTaskOutput.


        :param result_summaries: The result_summaries of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: list[ResultSummaryForListDiagnosticTaskOutput]
        """

        self._result_summaries = result_summaries

    @property
    def start_time(self):
        """Gets the start_time of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The start_time of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this ItemForListDiagnosticTaskOutput.


        :param start_time: The start_time of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: str
        """

        self._start_time = start_time

    @property
    def status(self):
        """Gets the status of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The status of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ItemForListDiagnosticTaskOutput.


        :param status: The status of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def suggestion(self):
        """Gets the suggestion of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The suggestion of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._suggestion

    @suggestion.setter
    def suggestion(self, suggestion):
        """Sets the suggestion of this ItemForListDiagnosticTaskOutput.


        :param suggestion: The suggestion of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: str
        """

        self._suggestion = suggestion

    @property
    def target_resources(self):
        """Gets the target_resources of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The target_resources of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: list[TargetResourceForListDiagnosticTaskOutput]
        """
        return self._target_resources

    @target_resources.setter
    def target_resources(self, target_resources):
        """Sets the target_resources of this ItemForListDiagnosticTaskOutput.


        :param target_resources: The target_resources of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: list[TargetResourceForListDiagnosticTaskOutput]
        """

        self._target_resources = target_resources

    @property
    def type(self):
        """Gets the type of this ItemForListDiagnosticTaskOutput.  # noqa: E501


        :return: The type of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ItemForListDiagnosticTaskOutput.


        :param type: The type of this ItemForListDiagnosticTaskOutput.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemForListDiagnosticTaskOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemForListDiagnosticTaskOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ItemForListDiagnosticTaskOutput):
            return True

        return self.to_dict() != other.to_dict()
