# coding: utf-8

"""
    vke

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ResourcesSummaryForListDiagnosticTaskOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'status': 'str',
        'target_resources': 'list[TargetResourceForListDiagnosticTaskOutput]'
    }

    attribute_map = {
        'count': 'Count',
        'status': 'Status',
        'target_resources': 'TargetResources'
    }

    def __init__(self, count=None, status=None, target_resources=None, _configuration=None):  # noqa: E501
        """ResourcesSummaryForListDiagnosticTaskOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._count = None
        self._status = None
        self._target_resources = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if status is not None:
            self.status = status
        if target_resources is not None:
            self.target_resources = target_resources

    @property
    def count(self):
        """Gets the count of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501


        :return: The count of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this ResourcesSummaryForListDiagnosticTaskOutput.


        :param count: The count of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def status(self):
        """Gets the status of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501


        :return: The status of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ResourcesSummaryForListDiagnosticTaskOutput.


        :param status: The status of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def target_resources(self):
        """Gets the target_resources of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501


        :return: The target_resources of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501
        :rtype: list[TargetResourceForListDiagnosticTaskOutput]
        """
        return self._target_resources

    @target_resources.setter
    def target_resources(self, target_resources):
        """Sets the target_resources of this ResourcesSummaryForListDiagnosticTaskOutput.


        :param target_resources: The target_resources of this ResourcesSummaryForListDiagnosticTaskOutput.  # noqa: E501
        :type: list[TargetResourceForListDiagnosticTaskOutput]
        """

        self._target_resources = target_resources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourcesSummaryForListDiagnosticTaskOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourcesSummaryForListDiagnosticTaskOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResourcesSummaryForListDiagnosticTaskOutput):
            return True

        return self.to_dict() != other.to_dict()
