# coding: utf-8

"""
    vke

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class UpdateClusterVersionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_token': 'str',
        'id': 'str',
        'ignore_precheck_warning': 'bool',
        'kubernetes_version': 'str',
        'operation': 'str'
    }

    attribute_map = {
        'client_token': 'ClientToken',
        'id': 'Id',
        'ignore_precheck_warning': 'IgnorePrecheckWarning',
        'kubernetes_version': 'KubernetesVersion',
        'operation': 'Operation'
    }

    def __init__(self, client_token=None, id=None, ignore_precheck_warning=None, kubernetes_version=None, operation=None, _configuration=None):  # noqa: E501
        """UpdateClusterVersionRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_token = None
        self._id = None
        self._ignore_precheck_warning = None
        self._kubernetes_version = None
        self._operation = None
        self.discriminator = None

        if client_token is not None:
            self.client_token = client_token
        self.id = id
        if ignore_precheck_warning is not None:
            self.ignore_precheck_warning = ignore_precheck_warning
        self.kubernetes_version = kubernetes_version
        if operation is not None:
            self.operation = operation

    @property
    def client_token(self):
        """Gets the client_token of this UpdateClusterVersionRequest.  # noqa: E501


        :return: The client_token of this UpdateClusterVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_token

    @client_token.setter
    def client_token(self, client_token):
        """Sets the client_token of this UpdateClusterVersionRequest.


        :param client_token: The client_token of this UpdateClusterVersionRequest.  # noqa: E501
        :type: str
        """

        self._client_token = client_token

    @property
    def id(self):
        """Gets the id of this UpdateClusterVersionRequest.  # noqa: E501


        :return: The id of this UpdateClusterVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UpdateClusterVersionRequest.


        :param id: The id of this UpdateClusterVersionRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def ignore_precheck_warning(self):
        """Gets the ignore_precheck_warning of this UpdateClusterVersionRequest.  # noqa: E501


        :return: The ignore_precheck_warning of this UpdateClusterVersionRequest.  # noqa: E501
        :rtype: bool
        """
        return self._ignore_precheck_warning

    @ignore_precheck_warning.setter
    def ignore_precheck_warning(self, ignore_precheck_warning):
        """Sets the ignore_precheck_warning of this UpdateClusterVersionRequest.


        :param ignore_precheck_warning: The ignore_precheck_warning of this UpdateClusterVersionRequest.  # noqa: E501
        :type: bool
        """

        self._ignore_precheck_warning = ignore_precheck_warning

    @property
    def kubernetes_version(self):
        """Gets the kubernetes_version of this UpdateClusterVersionRequest.  # noqa: E501


        :return: The kubernetes_version of this UpdateClusterVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._kubernetes_version

    @kubernetes_version.setter
    def kubernetes_version(self, kubernetes_version):
        """Sets the kubernetes_version of this UpdateClusterVersionRequest.


        :param kubernetes_version: The kubernetes_version of this UpdateClusterVersionRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and kubernetes_version is None:
            raise ValueError("Invalid value for `kubernetes_version`, must not be `None`")  # noqa: E501

        self._kubernetes_version = kubernetes_version

    @property
    def operation(self):
        """Gets the operation of this UpdateClusterVersionRequest.  # noqa: E501


        :return: The operation of this UpdateClusterVersionRequest.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this UpdateClusterVersionRequest.


        :param operation: The operation of this UpdateClusterVersionRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["Precheck", "Upgrade", "Pause", "Resume", "Abort"]  # noqa: E501
        if (self._configuration.client_side_validation and
                operation not in allowed_values):
            raise ValueError(
                "Invalid value for `operation` ({0}), must be one of {1}"  # noqa: E501
                .format(operation, allowed_values)
            )

        self._operation = operation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateClusterVersionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateClusterVersionRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateClusterVersionRequest):
            return True

        return self.to_dict() != other.to_dict()
