# coding: utf-8

"""
    vke

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class UpgradeNodePoolsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_token': 'str',
        'cluster_id': 'str',
        'ignore_precheck_warning': 'bool',
        'kubernetes_version': 'str',
        'node_pools': 'list[NodePoolForUpgradeNodePoolsInput]',
        'operation': 'str',
        'runtime': 'RuntimeForUpgradeNodePoolsInput',
        'upgrade_policy': 'UpgradePolicyForUpgradeNodePoolsInput'
    }

    attribute_map = {
        'client_token': 'ClientToken',
        'cluster_id': 'ClusterId',
        'ignore_precheck_warning': 'IgnorePrecheckWarning',
        'kubernetes_version': 'KubernetesVersion',
        'node_pools': 'NodePools',
        'operation': 'Operation',
        'runtime': 'Runtime',
        'upgrade_policy': 'UpgradePolicy'
    }

    def __init__(self, client_token=None, cluster_id=None, ignore_precheck_warning=None, kubernetes_version=None, node_pools=None, operation=None, runtime=None, upgrade_policy=None, _configuration=None):  # noqa: E501
        """UpgradeNodePoolsRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._client_token = None
        self._cluster_id = None
        self._ignore_precheck_warning = None
        self._kubernetes_version = None
        self._node_pools = None
        self._operation = None
        self._runtime = None
        self._upgrade_policy = None
        self.discriminator = None

        if client_token is not None:
            self.client_token = client_token
        self.cluster_id = cluster_id
        if ignore_precheck_warning is not None:
            self.ignore_precheck_warning = ignore_precheck_warning
        if kubernetes_version is not None:
            self.kubernetes_version = kubernetes_version
        if node_pools is not None:
            self.node_pools = node_pools
        if operation is not None:
            self.operation = operation
        if runtime is not None:
            self.runtime = runtime
        if upgrade_policy is not None:
            self.upgrade_policy = upgrade_policy

    @property
    def client_token(self):
        """Gets the client_token of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The client_token of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_token

    @client_token.setter
    def client_token(self, client_token):
        """Sets the client_token of this UpgradeNodePoolsRequest.


        :param client_token: The client_token of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: str
        """

        self._client_token = client_token

    @property
    def cluster_id(self):
        """Gets the cluster_id of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The cluster_id of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this UpgradeNodePoolsRequest.


        :param cluster_id: The cluster_id of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and cluster_id is None:
            raise ValueError("Invalid value for `cluster_id`, must not be `None`")  # noqa: E501

        self._cluster_id = cluster_id

    @property
    def ignore_precheck_warning(self):
        """Gets the ignore_precheck_warning of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The ignore_precheck_warning of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: bool
        """
        return self._ignore_precheck_warning

    @ignore_precheck_warning.setter
    def ignore_precheck_warning(self, ignore_precheck_warning):
        """Sets the ignore_precheck_warning of this UpgradeNodePoolsRequest.


        :param ignore_precheck_warning: The ignore_precheck_warning of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: bool
        """

        self._ignore_precheck_warning = ignore_precheck_warning

    @property
    def kubernetes_version(self):
        """Gets the kubernetes_version of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The kubernetes_version of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: str
        """
        return self._kubernetes_version

    @kubernetes_version.setter
    def kubernetes_version(self, kubernetes_version):
        """Sets the kubernetes_version of this UpgradeNodePoolsRequest.


        :param kubernetes_version: The kubernetes_version of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: str
        """

        self._kubernetes_version = kubernetes_version

    @property
    def node_pools(self):
        """Gets the node_pools of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The node_pools of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: list[NodePoolForUpgradeNodePoolsInput]
        """
        return self._node_pools

    @node_pools.setter
    def node_pools(self, node_pools):
        """Sets the node_pools of this UpgradeNodePoolsRequest.


        :param node_pools: The node_pools of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: list[NodePoolForUpgradeNodePoolsInput]
        """

        self._node_pools = node_pools

    @property
    def operation(self):
        """Gets the operation of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The operation of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this UpgradeNodePoolsRequest.


        :param operation: The operation of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["Precheck", "Upgrade", "Pause", "Resume", "Abort"]  # noqa: E501
        if (self._configuration.client_side_validation and
                operation not in allowed_values):
            raise ValueError(
                "Invalid value for `operation` ({0}), must be one of {1}"  # noqa: E501
                .format(operation, allowed_values)
            )

        self._operation = operation

    @property
    def runtime(self):
        """Gets the runtime of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The runtime of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: RuntimeForUpgradeNodePoolsInput
        """
        return self._runtime

    @runtime.setter
    def runtime(self, runtime):
        """Sets the runtime of this UpgradeNodePoolsRequest.


        :param runtime: The runtime of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: RuntimeForUpgradeNodePoolsInput
        """

        self._runtime = runtime

    @property
    def upgrade_policy(self):
        """Gets the upgrade_policy of this UpgradeNodePoolsRequest.  # noqa: E501


        :return: The upgrade_policy of this UpgradeNodePoolsRequest.  # noqa: E501
        :rtype: UpgradePolicyForUpgradeNodePoolsInput
        """
        return self._upgrade_policy

    @upgrade_policy.setter
    def upgrade_policy(self, upgrade_policy):
        """Sets the upgrade_policy of this UpgradeNodePoolsRequest.


        :param upgrade_policy: The upgrade_policy of this UpgradeNodePoolsRequest.  # noqa: E501
        :type: UpgradePolicyForUpgradeNodePoolsInput
        """

        self._upgrade_policy = upgrade_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpgradeNodePoolsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpgradeNodePoolsRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpgradeNodePoolsRequest):
            return True

        return self.to_dict() != other.to_dict()
