# coding: utf-8

"""
    cr

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from volcenginesdkcore.configuration import Configuration


class ProxyCacheForListRegistriesOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'endpoint': 'str',
        'skip_ssl_verify': 'bool',
        'type': 'str',
        'username': 'str'
    }

    attribute_map = {
        'endpoint': 'Endpoint',
        'skip_ssl_verify': 'SkipSSLVerify',
        'type': 'Type',
        'username': 'Username'
    }

    def __init__(self, endpoint=None, skip_ssl_verify=None, type=None, username=None, _configuration=None):  # noqa: E501
        """ProxyCacheForListRegistriesOutput - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._endpoint = None
        self._skip_ssl_verify = None
        self._type = None
        self._username = None
        self.discriminator = None

        if endpoint is not None:
            self.endpoint = endpoint
        if skip_ssl_verify is not None:
            self.skip_ssl_verify = skip_ssl_verify
        if type is not None:
            self.type = type
        if username is not None:
            self.username = username

    @property
    def endpoint(self):
        """Gets the endpoint of this ProxyCacheForListRegistriesOutput.  # noqa: E501


        :return: The endpoint of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this ProxyCacheForListRegistriesOutput.


        :param endpoint: The endpoint of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :type: str
        """

        self._endpoint = endpoint

    @property
    def skip_ssl_verify(self):
        """Gets the skip_ssl_verify of this ProxyCacheForListRegistriesOutput.  # noqa: E501


        :return: The skip_ssl_verify of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :rtype: bool
        """
        return self._skip_ssl_verify

    @skip_ssl_verify.setter
    def skip_ssl_verify(self, skip_ssl_verify):
        """Sets the skip_ssl_verify of this ProxyCacheForListRegistriesOutput.


        :param skip_ssl_verify: The skip_ssl_verify of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :type: bool
        """

        self._skip_ssl_verify = skip_ssl_verify

    @property
    def type(self):
        """Gets the type of this ProxyCacheForListRegistriesOutput.  # noqa: E501


        :return: The type of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ProxyCacheForListRegistriesOutput.


        :param type: The type of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def username(self):
        """Gets the username of this ProxyCacheForListRegistriesOutput.  # noqa: E501


        :return: The username of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ProxyCacheForListRegistriesOutput.


        :param username: The username of this ProxyCacheForListRegistriesOutput.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProxyCacheForListRegistriesOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProxyCacheForListRegistriesOutput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProxyCacheForListRegistriesOutput):
            return True

        return self.to_dict() != other.to_dict()
